# This workflow uses actions that are not certified by GitHub.  They are
# provided by a third-party and are governed by separate terms of service,
# privacy policy, and support documentation.
#
# This workflow will install a prebuilt Ruby version, install dependencies, and
# run tests and linters.
name: "Ruby on Rails CI"
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      # Add or replace dependency steps here
      
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@55283cc23133118229fd3f97f9336ee23a179fcf # v1.146.0
        with:
          bundler-cache: true
          
      # Add or replace database setup steps here
      # - name: Set up database schema
      #   run: bin/rails db:migrate
        
      # Add or replace test runners here
      - name: Run tests
        run: bin/rake
        env:
          POSTGRES_HOST: ${{ POSTGRES_HOST }}
          POSTGRES_PASSWORD: ${{ POSTGRES_PASSWORD }}
          POSTGRES_DATABASE: ${{ POSTGRES_DATABASE }}
          POSTGRES_USERNAME: ${{ POSTGRES_USERNAME }}

  build-image:
    name: Build Image
    needs: test
    runs-on: ubuntu-latest

    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      run: |
        docker build -t ${{ secrets.ECR_URL }}
        docker push ${{secrets.ECR_URL}}
